### ISSUE TITLE
Do you have any suggested library to use for Windows?

### ISSUE THREAD

**Issue by yo1995** [rpidanny/lg-ultrafine-brightness#1]
Hi,

Seems you build https://github.com/csujedihy/LG-Ultrafine-Brightness on Linux with `libusb`.
Just wonder if you have any suggestion for Windows library?

Thanks,

**Comment by rpidanny** [comment]
Hi @yo1995,

Sorry, I haven't really tried with Windows yet.

**Comment by yo1995** [comment]
never mind, just now I compiled a Windows version with libusb.
https://github.com/yo1995/Daily_GUI_Tools/tree/master/Tool_LG-Ultrafine-brightness
Thanks for your response 😄
